FROM busybox:1.33.0

RUN \
  mkdir -p /nina-app &&  \
  mkdir -p /nina-app/js-commons &&  \
  mkdir -p /nina-app/packages/commons &&  \
  mkdir -p /nina-app/packages/cy &&  \
  mkdir -p /nina-app/packages/data &&  \
  mkdir -p /nina-app/packages/db-migrations &&  \
  mkdir -p /nina-app/packages/hapi &&  \
  mkdir -p /nina-app/packages/pg-promise &&  \
  mkdir -p /nina-app/packages/svelte-commons &&  \
  mkdir -p /nina-app/packages/svelte

ADD \
  https://raw.githubusercontent.com/humpangle/wait-until/v0.1.1/wait-until \
  /nina-app

COPY ./entrypoint.sh /nina-app

WORKDIR /nina-app

######### ROOT FILES ##########
COPY  \
  ./.yarnrc \
  ./jest.config.js \
  ./package-scripts.js \
  ./package.json \
  ./postcss.config.js \
  ./svelte.config.js \
  ./yarn.lock \
  ./

########## SHARED FOLDER 1 ##########
COPY  \
  ./js-commons \
  ./js-commons/

######## COMMONS ##########
COPY  \
  ./packages/commons/package.json \
  ./packages/commons/package-scripts.js \
  ./packages/commons/tsconfig.json \
  ./packages/commons/

COPY  \
  ./packages/commons \
  ./packages/commons/
######## END COMMONS ########

######## CY ##########
COPY  \
  ./packages/cy/package.json \
  ./packages/cy/package-scripts.js \
  ./packages/cy/tsconfig.json \
  ./packages/cy/

COPY  \
  ./packages/cy \
  ./packages/cy/
######## END CY ########

######## DATA ##########
COPY  \
  ./packages/data/package.json \
  ./packages/data/package-scripts.js \
  ./packages/data/tsconfig.json \
  ./packages/data/

COPY  \
  ./packages/data \
  ./packages/data/
######## END DATA ########

######## DB-MIGRATIONS ##########
COPY  \
  ./packages/db-migrations/package.json \
  ./packages/db-migrations/package-scripts.js \
  ./packages/db-migrations/

COPY  \
  ./packages/db-migrations \
  ./packages/db-migrations/
######## END DB-MIGRATIONS ########

######## HAPI ##########
COPY  \
  ./packages/hapi/package.json \
  ./packages/hapi/package-scripts.js \
  ./packages/hapi/tsconfig.json \
  ./packages/hapi/

COPY  \
  ./packages/hapi \
  ./packages/hapi/
######## END HAPI ########

######## PG-PROMISE ##########
COPY  \
  ./packages/pg-promise/package.json \
  ./packages/pg-promise/package-scripts.js \
  ./packages/pg-promise/tsconfig.json \
  ./packages/pg-promise/

COPY  \
  ./packages/pg-promise \
  ./packages/pg-promise/
######## END PG-PROMISE ########

######## SVELTE-COMMONS ##########
COPY  \
  ./packages/svelte-commons/package.json \
  ./packages/svelte-commons/package-scripts.js \
  ./packages/svelte-commons/tsconfig.json \
  ./packages/svelte-commons/

COPY  \
  ./packages/svelte-commons \
  ./packages/svelte-commons/
######## END SVELTE-COMMONS ########

######## SVELTE ##########
COPY  \
  ./packages/svelte/package.json \
  ./packages/svelte/package-scripts.js \
  ./packages/svelte/tsconfig.json \
  ./packages/svelte/

COPY  \
  ./packages/svelte \
  ./packages/svelte/
######## END SVELTE ########

CMD ["/bin/sh"]