version: "3.4"
services:
  db:
    image: "postgres:13.1"
    ports:
      - "${DOCKER_HOST_DATABASE_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - "./docker/data/postgres-${COMPOSE_PROJECT_NAME}:/var/lib/postgresql/data"
  js-base:
    build:
      context: ./fe
      dockerfile: Dockerfile.base
      args:
        NODE_ENV: "${NODE_ENV}"
    image: nina-js-base
    env_file: "${DOCKER_ENV_FILE}"
    user: node
  js-commons:
    build:
      context: ./fe
      dockerfile: Dockerfile.commons
      args:
        NODE_ENV: "${NODE_ENV}"
    image: nina-js-commons
    env_file: "${DOCKER_ENV_FILE}"
    user: node
  js-all:
    stdin_open: true
    image: nina-js-all
    entrypoint:
      - /usr/local/bin/entrypoint.sh
    depends_on:
      - db
    env_file: "${DOCKER_ENV_FILE}"
    user: node
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${API_PORT}:${API_PORT}"
    volumes:
      - "./fe:/home/node/app"
      - "all_not_used_node_modules:/home/node/app/node_modules/"
      - "all_not_used_netlify:/home/node/app/.netlify/"
      - "all_not_used_commons_node_modules:/home/node/app/packages/commons/node_modules/"
      - "all_not_used_commons_coverage:/home/node/app/packages/commons/coverage/"
      - "all_not_used_data_node_modules:/home/node/app/packages/data/node_modules/"
      - "all_not_used_data_coverage:/home/node/app/packages/data/coverage/"
      - "all_not_used_db-migrations_node_modules:/home/node/app/packages/db-migrations/node_modules/"
      - "all_not_used_hapi_node_modules:/home/node/app/packages/hapi/node_modules/"
      - "all_not_used_hapi_coverage:/home/node/app/packages/hapi/coverage/"
      - "all_not_used_hapi_build:/home/node/app/packages/hapi/build/"
      - "all_not_used_pg-promise_node_modules:/home/node/app/packages/pg-promise/node_modules/"
      - "all_not_used_pg-promise_coverage:/home/node/app/packages/pg-promise/coverage/"
      - "all_not_used_svelte-commons_node_modules:/home/node/app/packages/svelte-commons/node_modules/"
      - "all_not_used_svelte-commons_coverage:/home/node/app/packages/svelte-commons/coverage/"
      - "all_not_used_svelte_node_modules:/home/node/app/packages/svelte/node_modules/"
      - "all_not_used_svelte_build:/home/node/app/packages/svelte/build/"
      - "all_not_used_cy:/home/node/app/packages/cy/"
  js-hapi:
    build:
      context: ./fe/packages/hapi
      dockerfile: Dockerfile.hapi
      args:
        NODE_ENV: "${NODE_ENV}"
    image: "nina-js-hapi-${NODE_ENV}"
    entrypoint:
      - /usr/local/bin/entrypoint.sh
    depends_on:
      - db
    env_file: "${DOCKER_ENV_FILE}"
    user: node
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - "./fe:/home/node/app"
      - "hapi_not_used_node_modules:/home/node/app/node_modules/"
      - "hapi_not_used_netlify:/home/node/app/.netlify/"
      - "hapi_not_used_commons_node_modules:/home/node/app/packages/commons/node_modules/"
      - "hapi_not_used_commons_coverage:/home/node/app/packages/commons/coverage/"
      - "hapi_not_used_data_node_modules:/home/node/app/packages/data/node_modules/"
      - "hapi_not_used_data_coverage:/home/node/app/packages/data/coverage/"
      - "hapi_not_used_db-migrations_node_modules:/home/node/app/packages/db-migrations/node_modules/"
      - "hapi_not_used_hapi_node_modules:/home/node/app/packages/hapi/node_modules/"
      - "hapi_not_used_hapi_coverage:/home/node/app/packages/hapi/coverage/"
      - "hapi_not_used_hapi_build:/home/node/app/packages/hapi/build/"
      - "hapi_not_used_pg-promise_node_modules:/home/node/app/packages/pg-promise/node_modules/"
      - "hapi_not_used_pg-promise_coverage:/home/node/app/packages/pg-promise/coverage/"
      - "hapi_not_used_cy:/home/node/app/packages/cy/"
      - "hapi_not_used_svelte-commons:/home/node/app/packages/svelte-commons/"
      - "hapi_not_used_svelte:/home/node/app/packages/svelte/"
  js-svelte:
    build:
      context: ./fe/packages/svelte
      dockerfile: Dockerfile.svelte
      args:
        NODE_ENV: "${NODE_ENV}"
    image: "nina-js-svelte-${NODE_ENV}"
    entrypoint:
      - /usr/local/bin/entrypoint.sh
    env_file: "${DOCKER_ENV_FILE}"
    user: node
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - "./fe:/home/node/app"
      - "svelte_not_used_node_modules:/home/node/app/node_modules/"
      - "svelte_not_used_netlify:/home/node/app/.netlify/"
      - "svelte_not_used_commons_node_modules:/home/node/app/packages/commons/node_modules/"
      - "svelte_not_used_commons_coverage:/home/node/app/packages/commons/coverage/"
      - "svelte_not_used_svelte-commons_node_modules:/home/node/app/packages/svelte-commons/node_modules/"
      - "svelte_not_used_svelte-commons_coverage:/home/node/app/packages/svelte-commons/coverage/"
      - "svelte_not_used_svelte_node_modules:/home/node/app/packages/svelte/node_modules/"
      - "svelte_not_used_svelte_build:/home/node/app/packages/svelte/build/"
      - "svelte_not_used_cy:/home/node/app/packages/cy/"
      - "svelte_not_used_data:/home/node/app/packages/data/"
      - "svelte_not_used_db-migrations:/home/node/app/packages/db-migrations/"
      - "svelte_not_used_hapi:/home/node/app/packages/hapi/"
      - "svelte_not_used_pg-promise:/home/node/app/packages/pg-promise/"
volumes:
  all_not_used_node_modules:
  all_not_used_netlify:
  all_not_used_commons_node_modules:
  all_not_used_commons_coverage:
  all_not_used_data_node_modules:
  all_not_used_data_coverage:
  all_not_used_db-migrations_node_modules:
  all_not_used_hapi_node_modules:
  all_not_used_hapi_coverage:
  all_not_used_hapi_build:
  all_not_used_pg-promise_node_modules:
  all_not_used_pg-promise_coverage:
  all_not_used_svelte-commons_node_modules:
  all_not_used_svelte-commons_coverage:
  all_not_used_svelte_node_modules:
  all_not_used_svelte_build:
  all_not_used_cy:
  hapi_not_used_node_modules:
  hapi_not_used_netlify:
  hapi_not_used_commons_node_modules:
  hapi_not_used_commons_coverage:
  hapi_not_used_data_node_modules:
  hapi_not_used_data_coverage:
  hapi_not_used_db-migrations_node_modules:
  hapi_not_used_hapi_node_modules:
  hapi_not_used_hapi_coverage:
  hapi_not_used_hapi_build:
  hapi_not_used_pg-promise_node_modules:
  hapi_not_used_pg-promise_coverage:
  hapi_not_used_cy:
  hapi_not_used_svelte-commons:
  hapi_not_used_svelte:
  svelte_not_used_node_modules:
  svelte_not_used_netlify:
  svelte_not_used_commons_node_modules:
  svelte_not_used_commons_coverage:
  svelte_not_used_svelte-commons_node_modules:
  svelte_not_used_svelte-commons_coverage:
  svelte_not_used_svelte_node_modules:
  svelte_not_used_svelte_build:
  svelte_not_used_cy:
  svelte_not_used_data:
  svelte_not_used_db-migrations:
  svelte_not_used_hapi:
  svelte_not_used_pg-promise:
